baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Yusei Ito
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Vitae
          url: vitae/
          weight: 2
        - name: Papers
          url: papers/
          weight: 2
        - name: Talks
          url: talks/
          weight: 2

params:
    description: "I am a Ph.D. student at Osaka University in Japan. My research focuses on AI for science, particularly the analysis of physical-measurement data, experimental design, and AI-assisted strategies that accelerate materials discovery. Through these AI-driven approaches, I aim to advance scientific breakthroughs and foster innovation."
    author: Yusei Ito
    googleAnalyticsID: "G-3GHZR90GBH"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data", "talks", "vitae"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yusei Ito
          subtitle: "I am a Ph.D. student at Osaka University in Japan. My research focuses on AI for science, particularly the analysis of physical-measurement data, experimental design, and AI-assisted strategies that accelerate materials discovery. Through these AI-driven approaches, I aim to advance scientific breakthroughs and foster innovation."
          imageUrl: "self_photo.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Yusei Ito
          buttons:
            - name: Papers
              url: papers/
            - name: Talks
              url: talks/
            - name: Vitae
              url: vitae/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yusei_ito@ap.eng.osaka-u.ac.jp
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/Yusei-Ito
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ni-EMfcAAAAJ&hl=ja

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yusei Ito"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
